"""empty message

Revision ID: 59225991d5a7
Revises: 90ce88bec2bb
Create Date: 2018-07-03 18:05:55.084086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59225991d5a7'
down_revision = '90ce88bec2bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('email', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
