"""empty message

Revision ID: 90ce88bec2bb
Revises: c60f4bf76d9f
Create Date: 2018-07-03 18:03:48.150097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90ce88bec2bb'
down_revision = 'c60f4bf76d9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('name', sa.String(length=50), nullable=True))
    op.drop_column('tag', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('username', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('tag', 'name')
    # ### end Alembic commands ###
