"""empty message

Revision ID: e4128c8678a9
Revises: 106c82cee2d6
Create Date: 2018-08-03 00:13:07.757385

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4128c8678a9'
down_revision = '106c82cee2d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('telephone', sa.String(length=11), nullable=False))
    op.drop_index('teltphone', table_name='front_user')
    op.create_unique_constraint(None, 'front_user', ['telephone'])
    op.drop_column('front_user', 'teltphone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('teltphone', mysql.VARCHAR(length=11), nullable=False))
    op.drop_constraint(None, 'front_user', type_='unique')
    op.create_index('teltphone', 'front_user', ['teltphone'], unique=True)
    op.drop_column('front_user', 'telephone')
    # ### end Alembic commands ###
