"""add user confirmed token

Revision ID: 827a5c3e8f4e
Revises: 
Create Date: 2018-06-21 17:31:22.812395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827a5c3e8f4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
